### ISSUE TITLE
Plugin not compatible with API v2?

### ISSUE THREAD

**Issue by davidlamb** [RusticiSoftware/SCORMCloud_WordPressPlugin#15]
Is this plugin supported anymore? If not you should make that more clear on the Wordpress plugin site.

I get multiple errors when trying to use this plugin, but I think the most relevant error is:

Fatal error: Uncaught Exception: SCORM Cloud Error : 300 - Account is not authorized to use the v1 API. We block v1 API requests on new accounts because the v1 API is being deprecated. Instead, please use the v2 API, https://cloud.scorm.com/docs/quick_start/overview/. If you have any questions, feel free to contact support@rusticisoftware.com in /home/customer/www/website/public_html/wp-content/plugins/scormcloud/SCORMCloud_PHPLibrary/ServiceRequest.php:149 Stack trace: #0 /home/customer/www/website/public_html/wp-content/plugins/scormcloud/SCORMCloud_PHPLibrary/ServiceRequest.php(91): ServiceRequest::AssertNoErrorAndReturnXml('<?xml version="...') #1 /home/customer/www/website/public_html/wp-content/plugins/scormcloud/SCORMCloud_PHPLibrary/AccountService.php(52): ServiceRequest->CallService('rustici.reporti...') #2 /home/customer/www/website/public_html/wp-content/plugins/scormcloud/scormcloudplugin.php(128): AccountService->GetAccountInfo() #3 /home/customer/www/website/public_html/wp-content/plugins/scormcl in /home/customer/www/website/public_html/wp-content/plugins/scormcloud/SCORMCloud_PHPLibrary/ServiceRequest.php on line 149

**Comment by brianrogers** [comment]
Hello, we are currently in the testing phase of the new plug-in updates. We are removing v1 API from SCORM Cloud and all new accounts are setup to use the v2 API. Hopefully we will have this ready for users in the next week or so. We will be updating all the online docs at that time and pushing users to the new plug-in that uses v2 API.

thanks.

**Comment by davidlamb** [comment]
Thanks! Hopefully it will be resolved then.

**Comment by brianrogers** [comment]
The new default branch is v2.x and it works with v2 Cloud API.
