### ISSUE TITLE
can you guys merge my fork or make me collab?

### ISSUE THREAD

**Issue by bretweinraub** [RusticiSoftware/SCORMCloud_WordPressPlugin#5]
basically; the plugin stack traces when updates are made to the user profile, and there isn't a first or last name in the profile defined.

thx

**Comment by nathaninlatin** [comment]
Hi, Bret.

Sorry this has gone without an answer for so long. Pull requests notify me in a way I can't ignore, while this issue was lost in my inbox.

You should be able to push your branch of the wordpress plugin to github and then create a pull request against the master branch. That pull request will be reviewed and merged.

If you have any questions, I'll try and watch this issue over the next few days. Also feel free to create a zendesk ticket.

--
Nathan

**Comment by bretweinraub** [comment]
Hi Nate -

It seems it is already merged!

Thanks,
Bret

On Mon, May 18, 2015 at 10:49 PM, Nathan S <notifications@github.com> wrote:

> Hi, Bret.
>
> Sorry this has gone without an answer for so long. Pull requests notify me
> in a way I can't ignore, while this issue was lost in my inbox.
>
> You should be able to push your branch of the wordpress plugin to github
> and then create a pull request against the master branch. That pull request
> will be reviewed and merged.
>
> If you have any questions, I'll try and watch this issue over the next few
> days. Also feel free to create a zendesk ticket.
>
> Nathan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RusticiSoftware/SCORMCloud_WordPressPlugin/issues/5#issuecomment-103206536>
> .
>



-- 
Bret D Weinraub | bret@aura-software.com | @bretweinraub
*US Direct*: (+1) 303 800 6758 | *US Mobile* (+1) 303 929 9087
*Swiss Direct*: (+41) 22 575 2303
*http://www.aura-software.com <http://www.aura-software.com>*

**Comment by bretweinraub** [comment]
https://github.com/RusticiSoftware/SCORMCloud_WordPressPlugin/commits/master

On Tue, May 19, 2015 at 11:32 AM, Bret Weinraub <bret@aura-software.com>
wrote:

> Hi Nate -
>
> It seems it is already merged!
>
> Thanks,
> Bret
>
> On Mon, May 18, 2015 at 10:49 PM, Nathan S <notifications@github.com>
> wrote:
>
>> Hi, Bret.
>>
>> Sorry this has gone without an answer for so long. Pull requests notify
>> me in a way I can't ignore, while this issue was lost in my inbox.
>>
>> You should be able to push your branch of the wordpress plugin to github
>> and then create a pull request against the master branch. That pull request
>> will be reviewed and merged.
>>
>> If you have any questions, I'll try and watch this issue over the next
>> few days. Also feel free to create a zendesk ticket.
>>
>> Nathan
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/RusticiSoftware/SCORMCloud_WordPressPlugin/issues/5#issuecomment-103206536>
>> .
>>
>
>
>
> --
> Bret D Weinraub | bret@aura-software.com | @bretweinraub
> *US Direct*: (+1) 303 800 6758 | *US Mobile* (+1) 303 929 9087
> *Swiss Direct*: (+41) 22 575 2303
> *http://www.aura-software.com <http://www.aura-software.com>*
>
>
>


-- 
Bret D Weinraub | bret@aura-software.com | @bretweinraub
*US Direct*: (+1) 303 800 6758 | *US Mobile* (+1) 303 929 9087
*Swiss Direct*: (+41) 22 575 2303
*http://www.aura-software.com <http://www.aura-software.com>*

**Comment by nathaninlatin** [comment]
Oh, good. We _are_ better about addressing PRs than we are github issues.

I'm going to go ahead and close this. Thank you.
